Problem: Only depends on our own cycle, not that of our dependencies
Solution: Find cycles in transitive dependencies, add to our
transitive dependencies.

Builds integration-tests, but does not build racket-doc.

    cycles ((compatibility-doc data-doc db-doc distributed-places-doc draw-doc drracket drracket-tool-doc errortrace-doc future-visualizer gui-doc macro-debugger math-doc mzscheme-doc net-cookies-doc net-doc parser-tools-doc pict-doc planet-doc plot-doc profile-doc r5rs-doc r6rs-doc racket-doc rackunit-doc readline-doc scribble-doc slideshow-doc srfi-doc string-constants-doc syntax-color-doc trace typed-racket-doc web-server-doc xrepl-doc))
    error: infinite recursion encountered, at undefined position

It seems we are failing to detect cycles within cycles?
racket-doc->distributed-places->distributes-places-doc->racket-doc
means distributed-places is part of the cycle, but it's not
included in the detected cycle.

 - Disable unit tests, they are writeten for the imperative code, not our current
   functional code. The integration tests have about the same coverage.