Problem: release: Depends on the nixpkgs pin to evaluate
    error: cannot import '/nix/store/[ . . . ]-source', since path
        '/nix/store/[ . . . ]-source.drv' is not valid, at
        [ . . . ]/racket2nix/pkgs/default.nix:1:10

Solution: Add a workaround: Make sure nixpkgs is built first.